apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "nginx-rootless.fullname" . }}
  labels:
    {{- include "nginx-rootless.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "2"
    link.argocd.argoproj.io/external-link: http://{{ tpl .Values.routeHostname . }}
    {{- include "nginx-rootless.annotations" . | nindent 4 }}
spec:
  host: {{ tpl .Values.routeHostname . }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ include "nginx-rootless.fullname" . }}
    weight: 100
  wildcardPolicy: None
