apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-rootless.fullname" . }}
  labels:
    {{- include "nginx-rootless.labels" . | nindent 4 }}
  annotations:                                                                                                                                                               
    "helm.sh/hook-weight": "1"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-rootless.selectorLabels" . | nindent 4 }}
