apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: bgd-dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: apps/bgd/overlays/dev
    repoURL: https://github.com/achelouah/openshift-gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
