apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: nginx-noroot
  name: nginx-noroot
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: nginx-noroot
