apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rootless-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: nginx-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/nginx-helm/nginx-rootless
    repoURL: https://github.com/achelouah/openshift-gitops-examples
    targetRevision: main
    helm:
      valueFiles:
        - values-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
