apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: bgd
  annotations:
    link.argocd.argoproj.io/external-link: http://bgd-bgd.apps-crc.testing
spec:
  host: bgd-bgd.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: bgd
    weight: 100
